// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(BibliotekaContext))]
    partial class BibliotekaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Backend.Models.Biblioteka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Adresa");

                    b.Property<string>("Naziv")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Biblioteka");
                });

            modelBuilder.Entity("Backend.Models.Knjiga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Autor");

                    b.Property<int>("BrStrana")
                        .HasColumnType("int")
                        .HasColumnName("BrStrana");

                    b.Property<int>("GodIzdavanja")
                        .HasColumnType("int")
                        .HasColumnName("GodIzdavanja");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int")
                        .HasColumnName("Kolicina");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv ");

                    b.Property<int?>("OdeljenjeID")
                        .HasColumnType("int");

                    b.Property<int>("PozUredu")
                        .HasColumnType("int")
                        .HasColumnName("PozUredu");

                    b.Property<int>("Red")
                        .HasColumnType("int")
                        .HasColumnName("Red");

                    b.HasKey("ID");

                    b.HasIndex("OdeljenjeID");

                    b.ToTable("Knjiga");
                });

            modelBuilder.Entity("Backend.Models.Odeljenje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BibliotekaID")
                        .HasColumnType("int");

                    b.Property<int>("BrPolicaPoRedu")
                        .HasColumnType("int")
                        .HasColumnName("BrPolicaPoRedu");

                    b.Property<int>("BrojRedova")
                        .HasColumnType("int")
                        .HasColumnName("BrojRedova");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.HasIndex("BibliotekaID");

                    b.ToTable("Odeljenje");
                });

            modelBuilder.Entity("Backend.Models.Knjiga", b =>
                {
                    b.HasOne("Backend.Models.Odeljenje", null)
                        .WithMany("Knjige")
                        .HasForeignKey("OdeljenjeID");
                });

            modelBuilder.Entity("Backend.Models.Odeljenje", b =>
                {
                    b.HasOne("Backend.Models.Biblioteka", null)
                        .WithMany("Odeljenja")
                        .HasForeignKey("BibliotekaID");
                });

            modelBuilder.Entity("Backend.Models.Biblioteka", b =>
                {
                    b.Navigation("Odeljenja");
                });

            modelBuilder.Entity("Backend.Models.Odeljenje", b =>
                {
                    b.Navigation("Knjige");
                });
#pragma warning restore 612, 618
        }
    }
}
